version: "3.7"

networks:
  frontend:
  backend:

volumes:
  db-transcendence:
    driver_opts:
      type: none
      device: $POSTGRES_DATAPATH
      o: bind

services:

  proxy:
    container_name: "nginx-transcendence"
    image: nginx
    ports:
      - '80:80'
    environment:
      NGINX_HOST: $SERVER_URL
      NGINX_PORT: 80
    networks:
      - frontend

  front:
    container_name: "react-transcendence"
    image: "react:transcendence"
    restart: unless-stopped
    init: true
    environment:
      REACT_APP_SERVER_IP: $SERVER_URL
    ports:
      - 5000:3000
    networks:
      - frontend
    build:
      context: containers/react-transcendence/

  api:
    container_name: "nest-transcendence"
    image: "nest:transcendence"
    restart: unless-stopped
    init: true
    ports:
      - 3000:3000
    volumes:
      - $POSTGRES_DATAPATH:$PGDATA
    networks:
      - frontend
      - backend
    env_file:
        - .env
    build:
      context: .
      dockerfile: containers/nest-transcendence/Dockerfile

  db:
    container_name: "postgres-transcendence"
    image: postgres
    restart: unless-stopped
    init: true
    env_file:
        - .env
# ================== TO REMOVE =================================
    ports:
      - 5432:5432
# ==============================================================
    networks:
      - backend
