version: "3.7"

networks:
  frontend:
  backend:

services:

  react:
    container_name: "react-transcendance"
    image: "react:transcendance"
    restart: unless-stopped
    init: true
    ports:
      - 3000:3000
    networks:
      - frontend
    env_file:
        - .env
    build:
      context: containers/react-transcendance/

  nest:
    container_name: "nest-transcendance"
    image: "nest:transcendance"
    restart: unless-stopped
    init: true
    ports:
      - 3001:3000
    networks:
      - frontend
      - backend
    env_file:
        - .env
    build:
      context: containers/nest-transcendance/

